### ISSUE TITLE
Next steps (task list)

### ISSUE THREAD

**Issue by voaneves** [voaneves/colab-rl#1]
To-do:
- [x] Add relative_pos argument;
- [x] Bring implementation from the test file to the main file;
- [x] Add multi-step returns argument;
- [ ] Find out what change in the lastest code made me lose performance (worse results).
- [ ] Add Noisy-Nets support.
- [ ] Add Tensorflow 1.12 and python 3.7 support.
- [ ] Finish README.md.
- [ ] Add KFAC and Shampoo as optimizer options;
- [ ] Complete documentation before releasing A2C algorithm.
- [ ] Release A2C algorithm.
- [ ] Release ACER algorithm.
- [ ] Find best possible config and create a Google Colab for testing.

**Comment by voaneves** [comment]
https://github.com/jakevdp/PythonDataScienceHandbook/pull/149/files

**Comment by voaneves** [comment]
https://img.shields.io/badge/Made%20with-Keras-red.svg

**Comment by voaneves** [comment]
Closing this issue because I'm migrating my task list to Microsoft To-do.
